version: '3.8'
services:
    web:
        container_name: web
        build: .
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py custom-superuser && python manage.py runserver 0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - 10555:8000
        depends_on:
        - db
    db:
        image: postgres
        container_name: db
        environment: 
            - POSTGRES_DB=exam_allocation
            - POSTGRES_USER=postgres
            - POSTGRES_HOST_PASSWORD=password 
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - pgdata:/var/lib/postgres/data
volumes:
    pgdata:
    