version: '3.8'
services:
    web:
        container_name: web
        build: .
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py custom-superuser && python manage.py runserver 0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - 10555:8000
        depends_on:
            - db
            - redis

    db:
        image: postgres
        container_name: db
        environment: 
            - POSTGRES_DB=exam_allocation
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password 
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - pgdata:/var/lib/postgres/data

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"

    rqworker:
        container_name: rqworker
        build: .
        command: bash -c "python manage.py rqworker default --with-scheduler"
        volumes:
            - .:/code
        depends_on:
            - redis
            - db

volumes:
    pgdata: